id: IB9D3C9D9
ocr_import_info:
  timestamp: '2023-10-06T09:40:01.405771+00:00'
  batch_id: batch-6cec
  ocr_engine: GoogleVisionEngine
  ocr_model_type: builtin/weekly
  ocr_lang_hint: ''
  software_id: ocr-pipelines@v0.1.11
  sponsor: Dharmakyab
  sponsor_consent: true
  op_import_options: {}
  op_import_version: 0.11.7
default_language: bo
source: https://library.bdrc.io
initial_creation_type: ocr
imported: 2023-10-06 11:35:31.087566+00:00
last_modified: 2023-10-06 11:35:31.087572+00:00
source_metadata:
  id: http://purl.bdrc.io/resource/W1NLM3630
  status: http://purl.bdrc.io/admindata/StatusReleased
  access: http://purl.bdrc.io/admindata/AccessOpen
  reproduction_of: http://purl.bdrc.io/resource/MW1NLM3630
  copyright_status: http://purl.bdrc.io/resource/CopyrightPublicDomain
  title: སྒྲོལ་མའི་བསྟོད་པ་མཁས་པའི་གཙུག་རྒྱན་སོགས།
  languages:
  - bo
statistics:
  ocr_word_mean_confidence_index: 0.9497864467735099
  ocr_word_median_confidence_index: 0.9945209850000001
bases:
  I1NLM3630_001:
    source_metadata:
      id: http://purl.bdrc.io/resource/I1NLM3630_001
      total_pages: 328
      volume_number: 1
      volume_pages_bdrc_intro: 0
    order: 1
    base_file: I1NLM3630_001.txt
    statistics:
      ocr_word_median_confidence_index: 0.9945209850000001
      ocr_word_mean_confidence_index: 0.9497864467735099
copyright:
  status: Public domain
  notice: Public domain
  info_url: https://creativecommons.org/publicdomain/mark/1.0/
license: CC0
